//! Authoritative catalogue of slash commands.
//!
//! Three static datasets:
//!
//! - [`SLASH_COMMAND_SPECS`] — every spec the CLI knows about, in canonical
//!   display order.
//! - [`LOW_VALUE_DEFERRED_SLASH_COMMANDS`] — commands intentionally hidden
//!   from the default help/suggest surface (low signal, kept for
//!   compatibility).
//! - [`HIDDEN_SLASH_COMMANDS`] — commands that exist purely as aliases for
//!   internal flows and should never surface in suggestions.
//!
//! Keeping these tables in one module makes it cheap to audit catalog
//! drift against the registered handlers in `slash_registry`.

use super::SlashCommandSpec;
use core_types::CommandCategory;

pub(super) const SLASH_COMMAND_SPECS: &[SlashCommandSpec] = &[
    SlashCommandSpec {
        name: "help",
        aliases: &[],
        summary: "Show available slash commands",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "status",
        aliases: &["stats", "summary"],
        summary: "Show current session status",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "name",
        aliases: &[],
        summary: "Show or set this session's display name",
        argument_hint: Some("[name]"),
        resume_supported: true,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "compact",
        aliases: &[],
        summary: "Compact local session history",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "model",
        aliases: &[],
        summary: "Show or switch the active model",
        argument_hint: Some("[model]"),
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "permissions",
        aliases: &["sandbox"],
        summary: "Show or switch the active permission mode",
        argument_hint: Some("[read-only|workspace-write|danger-full-access]"),
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "clear",
        aliases: &[],
        summary: "Start a fresh local session",
        argument_hint: Some("[--confirm]"),
        resume_supported: true,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "cost",
        aliases: &[],
        summary: "Show cumulative token usage for this session",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "resume",
        aliases: &[],
        summary: "Load a saved session into the REPL",
        argument_hint: Some("<session-path>"),
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "config",
        aliases: &[],
        summary: "Inspect Claude config files or merged sections",
        argument_hint: Some("[env|hooks|model|plugins]"),
        resume_supported: true,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "mcp",
        aliases: &[],
        summary: "Inspect configured MCP servers and manage OAuth",
        argument_hint: Some("[list|show <server>|auth [list|<server>]|logout <server>|help]"),
        resume_supported: true,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "tools",
        aliases: &[],
        summary: "Open runtime tool toggles",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "memory",
        aliases: &[],
        summary: "Inspect loaded instruction/context files",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "dream",
        aliases: &[],
        summary: "Curate session lessons into long-term memory (verified + repeated only)",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "refine",
        aliases: &[],
        summary: "Evidence-backed tuning report: harness health, shadow routing, improve hand-off (applies nothing)",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "init",
        aliases: &[],
        summary: "Scaffold context.md, .zo/ settings, docs, and agent stubs",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "diff",
        aliases: &[],
        summary: "Show git diff for current workspace changes",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "version",
        aliases: &[],
        summary: "Show CLI version and build information",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "bughunter",
        aliases: &[],
        summary: "Inspect the codebase for likely bugs",
        argument_hint: Some("[scope]"),
        resume_supported: false,
        category: CommandCategory::Analysis,
    },
    SlashCommandSpec {
        name: "commit",
        aliases: &[],
        summary: "Generate a commit message and create a git commit",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "ship",
        aliases: &[],
        summary: "Run gates, commit captured changes, and push",
        argument_hint: Some("<commit-message>"),
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "pr",
        aliases: &[],
        summary: "Draft or create a pull request from the conversation",
        argument_hint: Some("[context]"),
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "issue",
        aliases: &[],
        summary: "Draft or create a GitHub issue from the conversation",
        argument_hint: Some("[context]"),
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "ultraplan",
        aliases: &[],
        summary: "Run a deep planning prompt with multi-step reasoning",
        argument_hint: Some("[task]"),
        resume_supported: false,
        category: CommandCategory::Analysis,
    },
    SlashCommandSpec {
        name: "council",
        aliases: &[],
        summary: "Run a multi-candidate council and compare the answers",
        argument_hint: Some("[task]"),
        resume_supported: false,
        category: CommandCategory::Analysis,
    },
    SlashCommandSpec {
        name: "distill",
        aliases: &[],
        summary: "Draft a proposed reusable skill from a repeatable workflow",
        argument_hint: Some("[topic]"),
        resume_supported: false,
        category: CommandCategory::Analysis,
    },
    SlashCommandSpec {
        name: "goal",
        aliases: &[],
        summary: "Run a bounded goal loop with typed validation and repair",
        argument_hint: Some(
            "[status|verify|pause|resume|clear|history|<goal> (--check <validator>|--until <command>) [--every <duration>] [--no-plan] [--max-turns <n>] [--token-budget <n>]]",
        ),
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "loop",
        aliases: &[],
        summary: "Create or manage session-local recurring prompt loops",
        argument_hint: Some(
            "[list|status|<count> <prompt>|<prompt>|every <duration> <prompt>|watch <glob> <prompt>|until <command> <prompt>|run|pause|resume|stop]",
        ),
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "teleport",
        aliases: &[],
        summary: "Jump to a file or symbol by searching the workspace",
        argument_hint: Some("<symbol-or-path>"),
        resume_supported: false,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "debug-tool-call",
        aliases: &[],
        summary: "Replay the last tool call with debug details",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "export",
        aliases: &[],
        summary: "Export the current conversation to a file",
        argument_hint: Some("[file]"),
        resume_supported: true,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "dump",
        aliases: &[],
        summary: "Open the raw transcript in $PAGER to search it (edit → $EDITOR)",
        argument_hint: Some("[edit]"),
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "session",
        aliases: &[],
        summary: "List, switch, or fork managed local sessions",
        argument_hint: Some("[list|switch <session-id>|fork [branch-name]]"),
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "plugin",
        aliases: &["plugins", "marketplace"],
        summary: "Manage installed plugins",
        argument_hint: Some(
            "[list|install <path>|enable <name>|disable <name>|uninstall <id>|update <id>]",
        ),
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "agents",
        aliases: &[],
        summary: "List configured agents",
        argument_hint: Some("[list|help]"),
        resume_supported: true,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "inbox",
        aliases: &["teaminbox"],
        summary: "Team inbox: list updates, ack, and include summaries (alias /teaminbox)",
        argument_hint: Some("[ack <update-id>]"),
        resume_supported: true,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "skills",
        aliases: &[],
        summary: "List or install available skills",
        argument_hint: Some("[list|install <path>|help]"),
        resume_supported: true,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "doctor",
        aliases: &[],
        summary: "Diagnose setup issues and environment health",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "restart",
        aliases: &[],
        summary: "Relaunch the newest build on disk, resuming this session",
        argument_hint: None,
        // Re-execs the running process; only meaningful in the live TUI, never in
        // a headless `--resume` run.
        resume_supported: false,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "login",
        aliases: &[],
        summary: "Sign in to an account (claude, openai, google); bare /login picks one",
        argument_hint: Some("[provider]"),
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "logout",
        aliases: &[],
        summary: "Disconnect an account; bare /logout picks one, /logout all clears every saved OAuth",
        argument_hint: Some("[account|all]"),
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "plan",
        aliases: &[],
        summary: "Toggle or inspect planning mode",
        argument_hint: Some("[on|off]"),
        resume_supported: true,
        category: CommandCategory::Analysis,
    },
    SlashCommandSpec {
        name: "deep",
        aliases: &[],
        summary: "Toggle the deep-lane gate (plan→implement→verify→retry)",
        argument_hint: Some("[check-cmd|off]"),
        resume_supported: false,
        category: CommandCategory::Analysis,
    },
    SlashCommandSpec {
        name: "auto",
        aliases: &[],
        summary: "Toggle reactive auto-verify of edits (interactive default)",
        argument_hint: Some("[check-cmd|on|off]"),
        resume_supported: false,
        category: CommandCategory::Analysis,
    },
    SlashCommandSpec {
        name: "review",
        aliases: &[],
        summary: "Run a diff-backed preflight review on current changes",
        argument_hint: Some("[scope]"),
        resume_supported: false,
        category: CommandCategory::Analysis,
    },
    SlashCommandSpec {
        name: "hunks",
        aliases: &[],
        summary: "Review hunk attribution and accept/reject changes",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Analysis,
    },
    SlashCommandSpec {
        name: "tasks",
        aliases: &[],
        summary: "List and inspect background tasks in the current process",
        argument_hint: Some("[list|get <id>|stop <id>]"),
        resume_supported: true,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "theme",
        aliases: &[],
        summary: "Switch the terminal color theme",
        argument_hint: Some("[theme-name]"),
        resume_supported: true,
        category: CommandCategory::Appearance,
    },
    SlashCommandSpec {
        name: "upgrade",
        aliases: &[],
        summary: "Check for and install CLI updates",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "usage",
        aliases: &[],
        summary: "Open the graphical usage dashboard",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "audit",
        aliases: &[],
        summary: "Show this session's tool-invocation ledger (counts, denials, routes)",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "rename",
        aliases: &[],
        summary: "Rename the current session",
        argument_hint: Some("<name>"),
        resume_supported: false,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "copy",
        aliases: &[],
        summary: "Copy conversation or output to clipboard",
        argument_hint: Some("[last|all]"),
        resume_supported: true,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "remote",
        aliases: &[],
        summary: "Open Remote onboarding or manage a Tailscale phone pairing",
        argument_hint: Some("[start|status|qr|rotate|stop|approve <code>|deny <code>]"),
        resume_supported: false,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "share",
        aliases: &[],
        summary: "Save the transcript to a local share artifact (.zo/share/)",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "feedback",
        aliases: &[],
        summary: "Submit feedback about the current session",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "hooks",
        aliases: &[],
        summary: "List and manage lifecycle hooks",
        argument_hint: Some("[list|run <hook>]"),
        resume_supported: true,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "files",
        aliases: &[],
        summary: "List files in the current context window",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "context",
        aliases: &[],
        summary: "Show the live context-window breakdown",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "reload-context",
        aliases: &[],
        summary: "Reload project instructions, memory, skills, and runtime config",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "effort",
        aliases: &[],
        summary: "Open the effort slider (low → smart); arg sets it directly",
        argument_hint: Some("[off|low|medium|high|xhigh|max|ultra|smart]"),
        resume_supported: true,
        category: CommandCategory::Appearance,
    },
    SlashCommandSpec {
        name: "fast",
        aliases: &[],
        summary: "Toggle fast/concise response mode",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Appearance,
    },
    SlashCommandSpec {
        name: "smart",
        aliases: &[],
        summary: "Manage or open Smart Model Router dashboard",
        argument_hint: Some(
            "[status|agents|doctor|on|off|pin|auto|reset|explore|learned|feedback|diversity|providers]",
        ),
        resume_supported: false,
        category: CommandCategory::Analysis,
    },
    SlashCommandSpec {
        name: "tier",
        aliases: &[],
        summary: "Manage the Architect PLAN/VERIFY model pool",
        // Kept in lockstep with `DEEP_TIER_USAGE` by
        // `tier_argument_hint_lists_every_parsed_action` — a hint that omits an
        // action the parser accepts is a feature nobody can find.
        argument_hint: Some("[add <model>|set <N> <model>|remove <model|N>|move <N> <M>|reset]"),
        resume_supported: false,
        category: CommandCategory::Analysis,
    },
    SlashCommandSpec {
        name: "new",
        aliases: &[],
        summary: "Start a new conversation (clear context)",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "connect",
        aliases: &[],
        summary: "Register a provider (deepseek, kimi, qwen, ollama, or a URL); bare /connect picks one",
        argument_hint: Some("[provider]"),
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "providers",
        aliases: &[],
        summary: "Every account and registered provider in one screen (add, edit, delete, disconnect)",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "exit",
        aliases: &[],
        summary: "Exit the REPL session",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "branch",
        aliases: &[],
        summary: "Create or switch git branches",
        argument_hint: Some("[name]"),
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "rewind",
        aliases: &[],
        summary: "List or restore workspace checkpoints",
        argument_hint: Some("[<turn> [force]]"),
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "desktop",
        aliases: &[],
        summary: "Open or manage the desktop app integration",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "ide",
        aliases: &[],
        summary: "Connect to a running IDE extension (diagnostics, diffs via MCP)",
        argument_hint: Some("[name]"),
        resume_supported: false,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "brief",
        aliases: &[],
        summary: "Toggle brief output mode",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Appearance,
    },
    SlashCommandSpec {
        name: "advisor",
        aliases: &[],
        summary: "Toggle advisor mode for guidance-only responses",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Appearance,
    },
    SlashCommandSpec {
        name: "insights",
        aliases: &[],
        summary: "Show AI-generated insights about the session",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Appearance,
    },
    SlashCommandSpec {
        name: "thinkback",
        aliases: &[],
        summary: "Replay the thinking process of the last response",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "release-notes",
        aliases: &[],
        summary: "Generate release notes from recent changes",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "security-review",
        aliases: &[],
        summary: "Run a security review on the codebase",
        argument_hint: Some("[scope]"),
        resume_supported: false,
        category: CommandCategory::Analysis,
    },
    SlashCommandSpec {
        name: "keybindings",
        aliases: &[],
        summary: "Show or configure keyboard shortcuts",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Appearance,
    },
    SlashCommandSpec {
        name: "privacy-settings",
        aliases: &[],
        summary: "View or modify privacy settings",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "output-style",
        aliases: &[],
        summary: "Switch output formatting style",
        argument_hint: Some("[style]"),
        resume_supported: true,
        category: CommandCategory::Appearance,
    },
    SlashCommandSpec {
        name: "add-dir",
        aliases: &[],
        summary: "Add an additional directory to the context",
        argument_hint: Some("<path>"),
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "allowed-tools",
        aliases: &[],
        summary: "Show or modify the allowed tools list",
        argument_hint: Some("[add|remove|list] [tool]"),
        resume_supported: true,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "api-key",
        aliases: &[],
        summary: "Show or set the Anthropic API key",
        argument_hint: Some("[key]"),
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "approve",
        aliases: &["yes", "y"],
        summary: "Approve a pending tool execution",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "deny",
        aliases: &["no", "n"],
        summary: "Deny a pending tool execution",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "undo",
        aliases: &[],
        summary: "Undo the last file write or edit",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "stop",
        aliases: &[],
        summary: "Stop the current generation",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "retry",
        aliases: &[],
        summary: "Retry the last failed message",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "paste",
        aliases: &[],
        summary: "Paste clipboard content as input",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Appearance,
    },
    SlashCommandSpec {
        name: "screenshot",
        aliases: &[],
        summary: "Take a screenshot and add to conversation",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Appearance,
    },
    SlashCommandSpec {
        name: "image",
        aliases: &[],
        summary: "Add an image file to the conversation",
        argument_hint: Some("<path>"),
        resume_supported: false,
        category: CommandCategory::Appearance,
    },
    SlashCommandSpec {
        name: "terminal-setup",
        aliases: &[],
        summary: "Configure terminal integration settings",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Appearance,
    },
    SlashCommandSpec {
        name: "search",
        aliases: &[],
        summary: "Search files in the workspace",
        argument_hint: Some("<query>"),
        resume_supported: false,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "listen",
        aliases: &[],
        summary: "Listen for voice input",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Appearance,
    },
    SlashCommandSpec {
        name: "speak",
        aliases: &[],
        summary: "Read the last response aloud",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Appearance,
    },
    SlashCommandSpec {
        name: "language",
        aliases: &[],
        summary: "Set the interface language",
        argument_hint: Some("[language]"),
        resume_supported: true,
        category: CommandCategory::Appearance,
    },
    SlashCommandSpec {
        name: "profile",
        aliases: &[],
        summary: "Show or switch user profile",
        argument_hint: Some("[name]"),
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "max-tokens",
        aliases: &[],
        summary: "Show or set the max output tokens",
        argument_hint: Some("[count]"),
        resume_supported: true,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "temperature",
        aliases: &[],
        summary: "Show or set the sampling temperature",
        argument_hint: Some("[value]"),
        resume_supported: true,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "system-prompt",
        aliases: &[],
        summary: "Show the active system prompt",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "tool-details",
        aliases: &[],
        summary: "Show detailed info about a specific tool",
        argument_hint: Some("<tool-name>"),
        resume_supported: true,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "format",
        aliases: &[],
        summary: "Format the last response in a different style",
        argument_hint: Some("[markdown|plain|json]"),
        resume_supported: false,
        category: CommandCategory::Appearance,
    },
    SlashCommandSpec {
        name: "pin",
        aliases: &[],
        summary: "Pin a message to persist across compaction",
        argument_hint: Some("[message-index]"),
        resume_supported: false,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "unpin",
        aliases: &[],
        summary: "Unpin a previously pinned message",
        argument_hint: Some("[message-index]"),
        resume_supported: false,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "bookmarks",
        aliases: &[],
        summary: "List or manage conversation bookmarks",
        argument_hint: Some("[add|remove|list]"),
        resume_supported: true,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "workspace",
        aliases: &["cwd"],
        summary: "Show or change the working directory",
        argument_hint: Some("[path]"),
        resume_supported: true,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "history",
        aliases: &[],
        summary: "Show conversation history summary",
        argument_hint: Some("[count]"),
        resume_supported: true,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "tokens",
        aliases: &[],
        summary: "Show token count for the current conversation",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "cache",
        aliases: &[],
        summary: "Show prompt cache statistics",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "notifications",
        aliases: &[],
        summary: "Show or configure notification settings",
        argument_hint: Some("[on|off|status]"),
        resume_supported: true,
        category: CommandCategory::Appearance,
    },
    SlashCommandSpec {
        name: "changelog",
        aliases: &[],
        summary: "Show recent changes to the codebase",
        argument_hint: Some("[count]"),
        resume_supported: true,
        category: CommandCategory::Appearance,
    },
    SlashCommandSpec {
        name: "test",
        aliases: &[],
        summary: "Run tests for the current project",
        argument_hint: Some("[filter]"),
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "lint",
        aliases: &[],
        summary: "Run linting for the current project",
        argument_hint: Some("[filter]"),
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "build",
        aliases: &[],
        summary: "Build the current project",
        argument_hint: Some("[target]"),
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "run",
        aliases: &[],
        summary: "Run a command in the project context",
        argument_hint: Some("<command>"),
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "git",
        aliases: &[],
        summary: "Run a git command in the workspace",
        argument_hint: Some("<subcommand>"),
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "stash",
        aliases: &[],
        summary: "Stash or unstash workspace changes",
        argument_hint: Some("[pop|list|apply]"),
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "blame",
        aliases: &[],
        summary: "Show git blame for a file",
        argument_hint: Some("<file> [line]"),
        resume_supported: true,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "log",
        aliases: &[],
        summary: "Show git log for the workspace",
        argument_hint: Some("[count]"),
        resume_supported: true,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "cron",
        aliases: &[],
        summary: "Manage scheduled tasks",
        argument_hint: Some("[list|add|remove]"),
        resume_supported: true,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "team",
        aliases: &[],
        summary: "Manage agent teams",
        argument_hint: Some("[list|create|delete]"),
        resume_supported: true,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "benchmark",
        aliases: &[],
        summary: "Run performance benchmarks",
        argument_hint: Some("[suite]"),
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "migrate",
        aliases: &[],
        summary: "Run pending data migrations",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "reset",
        aliases: &[],
        summary: "Reset configuration to defaults",
        argument_hint: Some("[section]"),
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "telemetry",
        aliases: &[],
        summary: "Show or configure telemetry settings",
        argument_hint: Some("[on|off|status]"),
        resume_supported: true,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "env",
        aliases: &[],
        summary: "Show environment variables visible to tools",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "project",
        aliases: &[],
        summary: "Show project detection info",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "templates",
        aliases: &[],
        summary: "List or apply prompt templates",
        argument_hint: Some("[list|apply <name>]"),
        resume_supported: false,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "explain",
        aliases: &[],
        summary: "Explain a file or code snippet",
        argument_hint: Some("<path> [line-range]"),
        resume_supported: false,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "refactor",
        aliases: &[],
        summary: "Suggest refactoring for a file or function",
        argument_hint: Some("<path> [scope]"),
        resume_supported: false,
        category: CommandCategory::Analysis,
    },
    SlashCommandSpec {
        name: "docs",
        aliases: &[],
        summary: "Generate or show documentation",
        argument_hint: Some("[path]"),
        resume_supported: false,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "fix",
        aliases: &[],
        summary: "Fix errors in a file or project",
        argument_hint: Some("[path]"),
        resume_supported: false,
        category: CommandCategory::Analysis,
    },
    SlashCommandSpec {
        name: "perf",
        aliases: &[],
        summary: "Analyze performance of a function or file",
        argument_hint: Some("<path>"),
        resume_supported: false,
        category: CommandCategory::Analysis,
    },
    SlashCommandSpec {
        name: "chat",
        aliases: &[],
        summary: "Switch to free-form chat mode",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "focus",
        aliases: &[],
        summary: "Focus context on specific files or directories",
        argument_hint: Some("<path> [path...]"),
        resume_supported: false,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "unfocus",
        aliases: &[],
        summary: "Remove focus from files or directories",
        argument_hint: Some("[path...]"),
        resume_supported: false,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "web",
        aliases: &[],
        summary: "Fetch and summarize a web page",
        argument_hint: Some("<url>"),
        resume_supported: false,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "map",
        aliases: &[],
        summary: "Show a visual map of the codebase structure",
        argument_hint: Some("[depth]"),
        resume_supported: true,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "symbols",
        aliases: &[],
        summary: "List symbols (functions, classes, etc.) in a file",
        argument_hint: Some("<path>"),
        resume_supported: true,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "references",
        aliases: &[],
        summary: "Find all references to a symbol",
        argument_hint: Some("<symbol>"),
        resume_supported: false,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "definition",
        aliases: &[],
        summary: "Go to the definition of a symbol",
        argument_hint: Some("<symbol>"),
        resume_supported: false,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "hover",
        aliases: &[],
        summary: "Show hover information for a symbol",
        argument_hint: Some("<symbol>"),
        resume_supported: true,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "diagnostics",
        aliases: &[],
        summary: "Show LSP diagnostics for a file",
        argument_hint: Some("[path]"),
        resume_supported: true,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "autofix",
        aliases: &[],
        summary: "Auto-fix all fixable diagnostics",
        argument_hint: Some("[path]"),
        resume_supported: false,
        category: CommandCategory::Analysis,
    },
    SlashCommandSpec {
        name: "multi",
        aliases: &[],
        summary: "Execute multiple slash commands in sequence",
        argument_hint: Some("<commands>"),
        resume_supported: false,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "macro",
        aliases: &[],
        summary: "Record or replay command macros",
        argument_hint: Some("[record|stop|play <name>]"),
        resume_supported: false,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "alias",
        aliases: &[],
        summary: "Create a command alias",
        argument_hint: Some("<name> <command>"),
        resume_supported: true,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "parallel",
        aliases: &[],
        summary: "Run commands in parallel subagents",
        argument_hint: Some("<count> <prompt>"),
        resume_supported: false,
        category: CommandCategory::Control,
    },
    SlashCommandSpec {
        name: "agent",
        aliases: &[],
        summary: "Manage sub-agents and spawned sessions",
        argument_hint: Some("[list|spawn|kill]"),
        resume_supported: true,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "subagent",
        aliases: &[],
        summary: "Control active subagent execution",
        argument_hint: Some("[list|steer <target> <msg>|kill <id>]"),
        resume_supported: true,
        category: CommandCategory::Discovery,
    },
    SlashCommandSpec {
        name: "reasoning",
        aliases: &[],
        summary: "Toggle extended reasoning mode",
        argument_hint: Some("[on|off|stream]"),
        resume_supported: true,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "budget",
        aliases: &[],
        summary: "Show or set token budget limits",
        argument_hint: Some("[show|set <limit>]"),
        resume_supported: true,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "rate-limit",
        aliases: &[],
        summary: "Configure API rate limiting",
        argument_hint: Some("[status|set <rpm>]"),
        resume_supported: true,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "metrics",
        aliases: &[],
        summary: "Show performance and usage metrics",
        argument_hint: None,
        resume_supported: true,
        category: CommandCategory::Session,
    },
    // ---- Promoted Lane B commands -----------------------------------------
    // The following commands came from the archived TypeScript catalog
    // (`src/reference_data/commands_snapshot.json`) and now have real
    // handlers. The remaining never-implemented catalog stubs were removed
    // from the CLI in 2026-07; unknown names fall back to did-you-mean.
    SlashCommandSpec {
        name: "ant-trace",
        aliases: &[],
        summary: "Trace ant-scale execution over a task",
        argument_hint: Some("[scope]"),
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "backfill-sessions",
        aliases: &[],
        summary: "Backfill archived sessions into the local store",
        argument_hint: Some("[range]"),
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "commit-push-pr",
        aliases: &[],
        summary: "Commit, push, and open a pull request in one step",
        argument_hint: Some("[context]"),
        resume_supported: false,
        category: CommandCategory::Workspace,
    },
    SlashCommandSpec {
        name: "extra-usage",
        aliases: &[],
        summary: "Purchase or inspect extra usage credits",
        argument_hint: None,
        resume_supported: false,
        category: CommandCategory::Session,
    },
    SlashCommandSpec {
        name: "perf-issue",
        aliases: &[],
        summary: "File a performance issue with attached traces",
        argument_hint: Some("[context]"),
        resume_supported: false,
        category: CommandCategory::Analysis,
    },
    SlashCommandSpec {
        name: "pr-comments",
        aliases: &["pr_comments"],
        summary: "Fetch and review comments on the active PR",
        argument_hint: Some("[pr]"),
        resume_supported: false,
        category: CommandCategory::Analysis,
    },
    SlashCommandSpec {
        name: "statusline",
        aliases: &[],
        summary: "Configure the REPL status line",
        argument_hint: Some("[template]"),
        resume_supported: false,
        category: CommandCategory::Session,
    },
];

pub(super) const LOW_VALUE_DEFERRED_SLASH_COMMANDS: &[&str] = &[
    "upgrade",
    "share",
    "desktop",
    "brief",
    "advisor",
    "insights",
    "thinkback",
    "release-notes",
    "security-review",
    "keybindings",
    "privacy-settings",
    "rename",
    "copy",
    // Niche-but-real commands: keep them reachable by exact name without
    // crowding the default help/suggest surface.
    "ant-trace",
    "backfill-sessions",
    "commit-push-pr",
    "extra-usage",
    "perf-issue",
    "pr-comments",
    "statusline",
];

pub(super) const HIDDEN_SLASH_COMMANDS: &[&str] = &[
    "output-style",
    "allowed-tools",
    "api-key",
    "approve",
    "deny",
    "undo",
    "stop",
    "retry",
    "paste",
    "screenshot",
    "image",
    "terminal-setup",
    "search",
    "listen",
    "speak",
    "language",
    "profile",
    "max-tokens",
    "temperature",
    "system-prompt",
    "tool-details",
    "format",
    "pin",
    "unpin",
    "bookmarks",
    "workspace",
    "history",
    "tokens",
    "cache",
    "notifications",
    "changelog",
    "test",
    "lint",
    "build",
    "run",
    "git",
    "stash",
    "blame",
    "log",
    "cron",
    "team",
    "benchmark",
    "migrate",
    "reset",
    "telemetry",
    "env",
    "project",
    "templates",
    "explain",
    "refactor",
    "docs",
    "fix",
    "perf",
    "chat",
    "focus",
    "unfocus",
    "web",
    "map",
    "symbols",
    "references",
    "definition",
    "hover",
    "diagnostics",
    "autofix",
    "multi",
    "macro",
    "alias",
    "parallel",
    "agent",
    "subagent",
    "reasoning",
    "budget",
    "rate-limit",
    "metrics",
];
